package com.jewel.greendao.auto;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jewel.model.ExamData;

import com.jewel.greendao.auto.ExamDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig examDataDaoConfig;

    private final ExamDataDao examDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        examDataDaoConfig = daoConfigMap.get(ExamDataDao.class).clone();
        examDataDaoConfig.initIdentityScope(type);

        examDataDao = new ExamDataDao(examDataDaoConfig, this);

        registerDao(ExamData.class, examDataDao);
    }
    
    public void clear() {
        examDataDaoConfig.clearIdentityScope();
    }

    public ExamDataDao getExamDataDao() {
        return examDataDao;
    }

}
